### ISSUE TITLE
Advice to SBI

### ISSUE THREAD

**Issue by wxjstz** [riscv/riscv-sbi-doc#10]
The sbi should provide a mechanism for the presence of detection functions. This facilitates error detection with the S-mode program and the expansion of the SBI function.

I recommend adding the following two interfaces.
```c
/*
 * function : int sbi_has_feature(uintptr_t fid);
 * description : this is used to detect whether sbi has a certain function.
 * parameter fid : id of the function to be detected
 * return :
 *		0  - sbi provides this feature
 *		-1 - sbi does not provide this feature
 */
int sbi_has_feature(uintptr_t fid);

/*
 * function : int sbi_errno(void);
 * description : This is used to detect whether sbi has a certain function.
 * return : wrong number(the error number needs to be defined in advance 
 *          and consistently backward compatible),0 - no error.
 */
int sbi_errno(void);
```

**Comment by atishp04** [comment]
@wxjstz : Thanks for the suggestions.
We already have a proposal to extend SBI that has these suggestions.
The discussion around it can be found here.
http://lists.infradead.org/pipermail/linux-riscv/2018-October/001974.html

**Comment by neuschaefer** [comment]
I am slightly worried that the `sbi_errno` will complicate things by introducing (more?) global state in the SBI implementation. (Or will it be hart-local state?)

Thus, I'd prefer the complete error code to be returned from the erroring SBI call itself.

**Comment by aswaterman** [comment]
Global errno (or even thread-local errno) would be a mistake.

I actually think the Linux approach works OK: return a single value, but values in the range {-511, -1} are considered errors, whereas return values in the range {0, 2^XLEN-512} are considered success.

Failing that, returning a struct seems OK.

**Comment by wxjstz** [comment]
@aswaterman Yes, but it can be solved by reference.
E.g:
```c
Int sbi_fxxx(...,type* out);
```

**Comment by wxjstz** [comment]
@aswaterman But you can not return 0 as success, because sib_getchar maybe return 0.

**Comment by aswaterman** [comment]
0 implies success. sbi_getchar is OK

**Comment by alistair23** [comment]
I don't think it makes sense to have a global error state. The SBI call should return all of the information needed. Having to probe for error information adds extra state complexity as well as overhead of M-Mode calls.

Setting the SBI error status in a pointer passed via the SBI call sounds like a good approach. It's similar to how other user space applications work and allows us in the future to return valid negative numbers when we don't have an error (as the error is set in the error arg).

Something like this
```
/* Returns the CPU that was started.
 * @err indicates an error ID if one occurred, otherwise 0.
 * @err can be NULL if no error detection is required.
*/
int start_cpu(int cpu_num,..., Error *err);
```

**Comment by palmer-dabbelt** [comment]
We're adding a bunch of error handling and probing stuff in v0.2, so I'm going to close this as it suggests a very specific approach and the current one is slightly different.
