### ISSUE TITLE
v0.2: Timer and IPI extensions are missing "Function Listing" tables

### ISSUE THREAD

**Issue by konrad-schwarz** [riscv/riscv-sbi-doc#33]
The Timer and IPI extensions are missing the "Function Listing" tables present in the other extensions.

Although the Timer and IPI extensions have only a single function each, it would be
forward-thinking to define the appropriate function IDs to enable extension in the future.

Also, without function IDs, the switch from the v0.1 legacy encoding to the standard encoding provides no benefit.

**Comment by atishp04** [comment]
I agree. Function IDs was assumed to be zero as the it is the only function. But it should be documented in the specification. I will send a patch. Thanks.

**Comment by atishp04** [comment]
The requested change is already merged. Closing this issue.
