### ISSUE TITLE
Function to retrieve the Machine ISA CSR ``misa'' missing 

### ISSUE THREAD

**Issue by konrad-schwarz** [riscv/riscv-sbi-doc#40]
I would expect a function `struct sbiret sbi_get_misa (void);` to be provided.

The Privileged Architecture Spec makes a clear case for this:

> We require that lower privilege levels execute environment calls
> instead of reading CPU registers to determine features available
> at each privilege level. This enables virtualization layers
> to alter the ISA observed at any level, and supports a much richer
> command interface without burdening hardware designs.

**Comment by JohnAZoidberg** [comment]
Can be closed, since #41 has been closed.
