### ISSUE TITLE
Extension identifier 0x735049 is "sPI", not "IPI"

### ISSUE THREAD

**Issue by jhauser-us** [riscv/riscv-sbi-doc#53]
The head of the IPI Extension section says
> IPI Extension, Extension ID: 0x735049 (IPI)

But bytes 0x73, 0x50, 0x49 are characters "sPI", not "IPI", so either the identifier number or the text equivalent is wrong in the document.

**Comment by avpatel** [comment]
Argh, really bad typo on our side.

I guess we need to improve our review process.

Thanks for catching.

I guess we can live with this typo ??
OR
Change it to correct value for SBI v0.3 ??

Regards,
Anup

**Comment by atishp04** [comment]
Sorry for typo. Fixed in #52

**Comment by atishp04** [comment]
Closing this as the PR is merged.
