### ISSUE TITLE
Send IPI: how to define the value of hart_mask and hart_mask_base

### ISSUE THREAD

**Issue by micnaelyuanfeng** [riscv/riscv-sbi-doc#68]
Hello folks,
I am enabling 2 harts on risc-v qemu and tries to send interrupt from hart 0 to hart 1. After reading documents, sending sbi_send_ipi is the right to do so, but how to assign hart_mask and hart_mask_base? I tried use bit filed to hart_mask, such 0b00000010 to say sending an interrupt to hart 1, but I did not receive any interrupt on hart 1.

Thanks in advance

**Comment by nylon7** [comment]
Maybe you can check your $mie/$mip(by GNU GDB), Is it same ?
