### ISSUE TITLE
LICENSE file needs full CC-BY-4.0 license text

### ISSUE THREAD

**Issue by jjscheel** [riscv/riscv-sbi-doc#75]
Good community practice includes the full license text in the file instead of linking to it.

Unless someone has an objection, I'll update the file with the text in the next couple days.  Please let me know if you have any concerns.

**Comment by jjscheel** [comment]
@atishp04, I'd relish your input on how best to accomplish this.  I'd gladly submit a PR or push directly to main.

**Comment by atishp04** [comment]
Sure. Please send a PR.

**Comment by jjscheel** [comment]
@atishp04, that should do it.  holler if you have any problems with my PR.

**Comment by jjscheel** [comment]
Done.  Closing.
